### ISSUE TITLE
Control multiple displays with single slider

### ISSUE THREAD

**Issue by Teneff** [MonitorControl/MonitorControl#334]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
When multiple displays of the same kind(model) are connected as I want to change the brightness for all of them and I have to go through all of them one by one.

**Describe the solution you'd like**
Adding "All" menu on top of the displays with sliders to change the brightness for all of the displays would be great
![image](https://user-images.githubusercontent.com/1176644/100318072-1a86bd00-2fc6-11eb-87e2-a8376ca79971.png)

**Describe alternatives you've considered**
Ideally the current brightness of each display would be mapped to the current internal display, and once the internal display's brightness changes by the sensor, the external displays' brightness would also change based on the mapping

**Comment by riobard** [comment]
I'd further suggest that the unified slider should be customizable for monitors with different maximum brightness. Usually you want all connected monitors to be on the same level of brightness, which implies that it's necessary to set a cap on monitors with higher maximum brightness (and potentially lower minimum brightness as well).

**Comment by waydabber** [comment]
We will continue to manage this issue here. Please follow that thread for developments! Thank you!

https://github.com/MonitorControl/MonitorControl/issues/418

**Comment by waydabber** [comment]
Just some info about the progress regarding this issue:

- [x] There is now polling for the internal screen + sliders are updating based on change which was implemented when solving https://github.com/MonitorControl/MonitorControl/issues/198. This works nicely whenever the ambient light sensor kicks in or the touchbar slider is used. This is a foundation to have the brightness replicated among other displays.
- [ ] Some other things are needed until proper synchronization can be done. These are #310, #418 and #570. These are interlocked issues and I am in progress of making it work.
- [ ] Once the above are done, this and #27 will logically follow.

**Comment by waydabber** [comment]
> I'd further suggest that the unified slider should be customizable for monitors with different maximum brightness. Usually you want all connected monitors to be on the same level of brightness, which implies that it's necessary to set a cap on monitors with higher maximum brightness (and potentially lower minimum brightness as well).

@riobard - setting caps and adjusting the brightness curve of the display will help in achieving some level uniformity among displays if somebody wants to do so.

**Comment by riobard** [comment]
That'll be super nice!
